### PR TITLE
Broadened version ranges of noSig for org.codehaus.plexus

### PR DESCRIPTION
**Pull request by aoindustries**
Reviewed all existing map entries for the "org.codehaus.plexus" groupId.
Expanded version ranges to cover all necessary noSig.

Discovered one-off signature on org.codehaus.plexus:plexus-utils:jar:sources:1.5.1

### CODE REVIEW

**Comment by aoindustries** [comment]
This concludes all "noSig" required for our current builds.  So, if desired, this would be a reasonable point to release a new pgp-keys-map version.

Beyond this, we have defined mappings for signatures of other artifacts used by our builds.  We have simply added key signatures based on what we see in the repository.  This will be enough to alert us when a newer version is released with a different key signature.

Since we do not have any special knowledge or authority on the remaining artifacts, is it appropriate to add observed signatures to this project?  If so, I'd be happy to add more of the signatures we've observed.

You may see our additional definitions, if desired:
https://github.com/aoindustries/pgp-keys-map/blob/959506a7ed60dd7cd172574958e899a71d2e198f/src/main/resources/com/aoapps/pgp/keys/map/pgp-keys-map.list#L78

**Comment by aoindustries** [comment]
I rebased while fixing a typo in the commit message.  We're also GPG signing Git commits now.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
I also adding keys by observation and verify:
 - email address in key if correspond with project name, domain
 - some of organization publish commiters keys like apache: https://people.apache.org/keys/committer/

**Comment by slawekjaranowski** [comment]
And answering to question - every new key with example of usage are welcome.

**Comment by aoindustries** [comment]
Thank you for the follow-up.  We may provide more pull requests in the future.  However, we look forward to your next release of this project.

**Pull request merged**
