### PR TITLE
Keys for verifyPluginDependencies

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by cobratbq** [comment]
For me it fails to complete due to signature not being recognized as a signature.
```
[ERROR] Failed to execute goal org.simplify4u.plugins:pgpverify-maven-plugin:1.9.0-SNAPSHOT:check (default) on project org-apache-maven-plugins-test: Failed to process signature '/home/danny/.m2/repository/org/apache/xmlgraphics/fop/0.95/fop-0.95.pom.asc' for artifact org.apache.xmlgraphics:fop:pom:0.95: File content is not a PGP signature. -> [Help 1]
```

GPG signature packets: `gpg --list-packets ...`
```
# off=0 ctb=a3 tag=8 hlen=1 plen=0 indeterminate
:compressed packet: algo=1
# off=2 ctb=90 tag=4 hlen=2 plen=13
:onepass_sig packet: keyid 8E1E35C66754351B
	version 3, sigclass 0x00, digest 2, pubkey 17, last=1
# off=17 ctb=ad tag=11 hlen=3 plen=5934
:literal data packet:
	mode b (62), created 1222628963, name="fop-0.95.pom",
	raw data: 5916 bytes
# off=5954 ctb=88 tag=2 hlen=2 plen=70
:signature packet: algo 17, keyid 8E1E35C66754351B
	version 4, created 1222628963, md5len 0, sigclass 0x00
	digest algo 2, begin of digest bf 9a
	hashed subpkt 2 len 4 (sig created 2008-09-28)
	subpkt 16 len 8 (issuer key ID 8E1E35C66754351B)
	data: [160 bits]
	data: [160 bits]
```
I have not investigated this any further yet. I provided the output of GPG. Maybe you already know what this is about. My wild guess is that the signature package contains unknown packets or something like that. However, it's only an educated guess.

**Comment by slawekjaranowski** [comment]
I had the same problem, so https://github.com/s4u/pgpverify-maven-plugin/issues/114 allows skip and set signature as bad if some problem occurs.

**Comment by slawekjaranowski** [comment]
We have issue for it: s4u/pgpverify-maven-plugin/issues/120

**Comment by cobratbq** [comment]
> I had the same problem, so [s4u/pgpverify-maven-plugin#114](https://github.com/s4u/pgpverify-maven-plugin/issues/114) allows skip and set signature as bad if some problem occurs.

Sure, but this means that I cannot successfully build this PR. Is that intentional? I would fix it before merging the changes.

**Comment by cobratbq** [comment]
I think you were right to think I did not use the latest snapshot.

However, now I run into a different issue: 2 packages marked as `noKey` are failing because I have the public key available.

I'm thinking it may be useful to add `hkps://keyserver.ubuntu.com` as a secondary keyserver for this project, so have more consistent results?
Or we can add the actual public key fingerprint next to `noKey` in the pgp keys map?

**Comment by cobratbq** [comment]
The build succeeds after cleaning the pgp keys cache. I have not checked every single addition. At this point, I think it would be overkill to do so, unless there is a good strategy for it.

**Pull request merged**
